[build]
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://generativelanguage.googleapis.com/:splat"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"

[context.production.environment]
  NODE_ENV = "production"
