[build]
  functions = "netlify/functions"
  publish = "." 
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/proxy"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
